
debug:
	@devilspie debug.ds
.PHONY: debug


println:
	@devilspie println.ds
.PHONY: println


boolean:
	@devilspie boolean.ds
.PHONY: boolean


begin:
	@devilspie begin.ds
.PHONY: begin


quit:
	@devilspie quit.ds
.PHONY: quit
